[package]
name = "inth-oauth2-async"
version = "0.19.0"
edition = "2021"

description = "OAuth2 client"
keywords = ["authentication", "authorization", "auth", "oauth"]

authors = ["Curtis McEnroe <programble@gmail.com>", "Bill Fraser <wfraser@codewise.org>"]
license = "ISC"

repository = "https://github.com/wfraser/inth-oauth2-async"
readme = "README.md"

[dependencies]
async-trait = "0.1.50"
lazy_static = "1.1.0"
serde = "1.0.8"
serde_derive = "1.0.5"
serde_json = "1.0.2"
url = "2.2.2"

# Reqwest client:
reqwest = { version = "0.11.3", optional = true }

# Hyper client:
base64 = { version = "0.13", optional = true }
http-body-util = { version = "0.1.0", optional = true }
hyper = { version = "1.0", optional = true }
hyper-util = { version = "0.1.0", features = ["client-legacy", "http1", "http2"], optional = true }
tokio = { version = "1.7", optional = true }
tower-service = {version = "0.3.1", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
hyper-util = { version = "0.1.0", features = ["tokio"] }
hyper-tls = "0.6.0"

[features]
default = ["reqwest-client"]
hyper-client = ["base64", "http-body-util", "hyper/client", "hyper/http1", "hyper/http2", "hyper-util", "tokio", "tower-service"]
reqwest-client = ["reqwest"]

[[example]]
name = "github"
required-features = ["reqwest-client"]

[[example]]
name = "google-web"
required-features = ["reqwest-client"]

[[example]]
name = "google-installed"
required-features = ["reqwest-client"]

[[example]]
name = "imgur"
required-features = ["reqwest-client"]

[[test]]
name = "auth_uri"
required-features = ["reqwest-client"]

[[test]]
name = "hyper-client"
required-features = ["hyper-client"]
